### ISSUE TITLE
Timestamp not sorted/merged

### ISSUE THREAD

**Issue by jbescos** [btiftik/consumer#1]
Hi Burak,

I was running it and I found the response was not properly sorted, for example you can see that timestamp 1579606114487 and 1579606114488 are displayed twice (it should be merged) and it should be sorted:

{"amount":-724.2516627432709,"timeStamp":1579606114486}
{"amount":5144.904787175346,"timeStamp":1579606114487}
{"amount":2896.0643796600925,"timeStamp":1579606114488}
{"amount":-1520.902895064139,"timeStamp":1579606114487}
{"amount":5744.362863736367,"timeStamp":1579606114488}

Think that producers could be different clients in different hosts that could have some miss matches in the timestamps. Even if they are running the same timestamps, there is always some delay in the network.

**Comment by btiftik** [comment]
Hello,

It was happening because there were 2 timestamps, one that was set by client when the message was generated and one that was set by the jms when the message was sent.
I am now just using the jms message timestamp which solved the issue. Is it part of the requirement to place the timestamp on the xml or can it be a part of the message in the header and be used that way? if so this should be enough.
Also I can only check this at night hence the delay, so I apologize for that.
As for different timestamps then I would need to timestamp at the broker, which I will need to look into later, I know there is a plugin for it. I assumed all the producers would at least be in the same machine for the sake of simplicity.
